---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Worklab:
    - Memos:
        href: https://memos.localhost/
        description: Effortlessly craft your impactful content
        container: memos
    - Grafana:
        href: https://grafana.localhost/
        description: Les métriques d'utilisation de vos resources.
        container: grafana
        # widget:
        #     type: grafana
        #     url: http://grafana:3000
        #     username: admin
        #     password: 
    - Vaultwarden:
        href: https://vaultwarden.localhost/
        description: Vaultwarden is a password manager for securely storing, managing, and sharing sensitive online data such as passwords and passkeys.
        container: vaultwarden
    - Harness Open Source:
        href: https://harness.localhost/
        description: Seamless Git integration, fast pipelines, and hosted development environments.
        container: harness

- Services:
    - Traefik:
        description: Votre reverse proxy local.
        container: traefik
        widget:
            type: traefik
            url: http://traefik:8080
    - Atuin:
        href: https://atuin.localhost/healthz
        description: Sync, search and backup shell history with Atuin
        container: atuin
    - Prometheus:
        container: prometheus
        widget:
            type: prometheus
            url: http://prometheus:9090
    