pageInfo:
  title: Work Lab
sections: # An array of sections
- name: Local
  icon: far fa-rocket
  items:
  - title: Vaultwarden
    description: An alternative server implementation of the Bitwarden Client API.
    icon: si-vaultwarden
    url: https://vaultwarden.localhost
  - title: Harness
    description: Harness Open Source offers an end-to-end software delivery platform that enhances productivity and accelerates software development cycles, eliminating the need to juggle disjointed software development tools.
    icon: fab fa-git
    url: https://harness.localhost
